version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: bg-company-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bg_company
      POSTGRES_USER: app
      POSTGRES_PASSWORD: super_password
    ports:
      - "5433:5432"
    volumes:
      - bg_company_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d bg_company"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  bg_company_db_data:
